// Dog Fight Game Code By CYM.

#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "MathHelperLibrary.generated.h"

/**
 * 
 */
UCLASS()
class PROJECTFRAMEWORK_API UMathHelperLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:

	/**
	* Find the smallest positive missing number in array that contains both
	* positive and negative integers.
	*/
	UFUNCTION(BlueprintCallable, Category="DogFight|Math")
	static int32 GetMinMissingPositiveNumber(TArray<int32> InArray, int32 MinNumber);

	/**
	 * Get a randomized order list generated by Fisher-Yates Shuffle algorithm.
	 * @param IndexArray Original index array to randomize.
	 * @return Array after randomization.
	 */
	UFUNCTION(BlueprintCallable, Category="DogFight|Math")
	static TArray<int32> RandomizedOrder(const TArray<int32>& IndexArray);
};
