// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Config_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Config_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "xresloader.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Config_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Config_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Config_2eproto;
class Card_cfg;
struct Card_cfgDefaultTypeInternal;
extern Card_cfgDefaultTypeInternal _Card_cfg_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Card_cfg* Arena::CreateMaybeMessage<::Card_cfg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum ECostType : int {
  CT_Unknown = 0,
  CT_Coin = 1,
  CT_Diamond = 2,
  ECostType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ECostType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ECostType_IsValid(int value);
constexpr ECostType ECostType_MIN = CT_Unknown;
constexpr ECostType ECostType_MAX = CT_Diamond;
constexpr int ECostType_ARRAYSIZE = ECostType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECostType_descriptor();
template<typename T>
inline const std::string& ECostType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ECostType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ECostType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ECostType_descriptor(), enum_t_value);
}
inline bool ECostType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ECostType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ECostType>(
    ECostType_descriptor(), name, value);
}
// ===================================================================

class Card_cfg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Card_cfg) */ {
 public:
  inline Card_cfg() : Card_cfg(nullptr) {}
  ~Card_cfg() override;
  explicit constexpr Card_cfg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Card_cfg(const Card_cfg& from);
  Card_cfg(Card_cfg&& from) noexcept
    : Card_cfg() {
    *this = ::std::move(from);
  }

  inline Card_cfg& operator=(const Card_cfg& from) {
    CopyFrom(from);
    return *this;
  }
  inline Card_cfg& operator=(Card_cfg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Card_cfg& default_instance() {
    return *internal_default_instance();
  }
  static inline const Card_cfg* internal_default_instance() {
    return reinterpret_cast<const Card_cfg*>(
               &_Card_cfg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Card_cfg& a, Card_cfg& b) {
    a.Swap(&b);
  }
  inline void Swap(Card_cfg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Card_cfg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Card_cfg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Card_cfg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Card_cfg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Card_cfg& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Card_cfg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Card_cfg";
  }
  protected:
  explicit Card_cfg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kIdFieldNumber = 1,
    kCostTypeFieldNumber = 3,
  };
  // string Name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // uint32 Id = 1;
  void clear_id();
  uint32_t id() const;
  void set_id(uint32_t value);
  private:
  uint32_t _internal_id() const;
  void _internal_set_id(uint32_t value);
  public:

  // uint32 CostType = 3 [(.org.xresloader.validator) = "ECostType", (.org.xresloader.field_description) = "Refer to ECostType"];
  void clear_costtype();
  uint32_t costtype() const;
  void set_costtype(uint32_t value);
  private:
  uint32_t _internal_costtype() const;
  void _internal_set_costtype(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Card_cfg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  uint32_t id_;
  uint32_t costtype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Config_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Card_cfg

// uint32 Id = 1;
inline void Card_cfg::clear_id() {
  id_ = 0u;
}
inline uint32_t Card_cfg::_internal_id() const {
  return id_;
}
inline uint32_t Card_cfg::id() const {
  // @@protoc_insertion_point(field_get:Card_cfg.Id)
  return _internal_id();
}
inline void Card_cfg::_internal_set_id(uint32_t value) {
  
  id_ = value;
}
inline void Card_cfg::set_id(uint32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Card_cfg.Id)
}

// string Name = 2;
inline void Card_cfg::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& Card_cfg::name() const {
  // @@protoc_insertion_point(field_get:Card_cfg.Name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Card_cfg::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Card_cfg.Name)
}
inline std::string* Card_cfg::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Card_cfg.Name)
  return _s;
}
inline const std::string& Card_cfg::_internal_name() const {
  return name_.Get();
}
inline void Card_cfg::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Card_cfg::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Card_cfg::release_name() {
  // @@protoc_insertion_point(field_release:Card_cfg.Name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Card_cfg::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Card_cfg.Name)
}

// uint32 CostType = 3 [(.org.xresloader.validator) = "ECostType", (.org.xresloader.field_description) = "Refer to ECostType"];
inline void Card_cfg::clear_costtype() {
  costtype_ = 0u;
}
inline uint32_t Card_cfg::_internal_costtype() const {
  return costtype_;
}
inline uint32_t Card_cfg::costtype() const {
  // @@protoc_insertion_point(field_get:Card_cfg.CostType)
  return _internal_costtype();
}
inline void Card_cfg::_internal_set_costtype(uint32_t value) {
  
  costtype_ = value;
}
inline void Card_cfg::set_costtype(uint32_t value) {
  _internal_set_costtype(value);
  // @@protoc_insertion_point(field_set:Card_cfg.CostType)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ECostType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ECostType>() {
  return ::ECostType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Config_2eproto
