// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xresloader_ue.proto

#include "xresloader_ue.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace org {
namespace xresloader {
namespace ue {
}  // namespace ue
}  // namespace xresloader
}  // namespace org
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_xresloader_5fue_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_xresloader_5fue_2eproto = nullptr;
const uint32_t TableStruct_xresloader_5fue_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_xresloader_5fue_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023xresloader_ue.proto\022\021org.xresloader.ue"
  "\032 google/protobuf/descriptor.proto*`\n\013lo"
  "ader_mode\022\032\n\026EN_LOADER_MODE_DEFAULT\020\000\022\031\n"
  "\025EN_LOADER_MODE_ENABLE\020\001\022\032\n\026EN_LOADER_MO"
  "DE_DISABLE\020\002:/\n\007key_tag\022\035.google.protobu"
  "f.FieldOptions\030\315\010 \001(\003:4\n\014ue_type_name\022\035."
  "google.protobuf.FieldOptions\030\316\010 \001(\t:8\n\020u"
  "e_type_is_class\022\035.google.protobuf.FieldO"
  "ptions\030\317\010 \001(\010:;\n\023ue_origin_type_name\022\035.g"
  "oogle.protobuf.FieldOptions\030\320\010 \001(\t:D\n\034ue"
  "_origin_type_default_value\022\035.google.prot"
  "obuf.FieldOptions\030\321\010 \001(\t:0\n\006helper\022\037.goo"
  "gle.protobuf.MessageOptions\030\315\010 \001(\t:8\n\016no"
  "t_data_table\022\037.google.protobuf.MessageOp"
  "tions\030\316\010 \001(\010:X\n\016default_loader\022\037.google."
  "protobuf.MessageOptions\030\317\010 \001(\0162\036.org.xre"
  "sloader.ue.loader_mode:8\n\016include_header"
  "\022\037.google.protobuf.MessageOptions\030\320\010 \003(\t"
  "b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_xresloader_5fue_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_xresloader_5fue_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_xresloader_5fue_2eproto = {
  false, false, 728, descriptor_table_protodef_xresloader_5fue_2eproto, "xresloader_ue.proto", 
  &descriptor_table_xresloader_5fue_2eproto_once, descriptor_table_xresloader_5fue_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_xresloader_5fue_2eproto::offsets,
  nullptr, file_level_enum_descriptors_xresloader_5fue_2eproto, file_level_service_descriptors_xresloader_5fue_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_xresloader_5fue_2eproto_getter() {
  return &descriptor_table_xresloader_5fue_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_xresloader_5fue_2eproto(&descriptor_table_xresloader_5fue_2eproto);
namespace org {
namespace xresloader {
namespace ue {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* loader_mode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xresloader_5fue_2eproto);
  return file_level_enum_descriptors_xresloader_5fue_2eproto[0];
}
bool loader_mode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< int64_t >, 3, false >
  key_tag(kKeyTagFieldNumber, int64_t{0});
const std::string ue_type_name_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  ue_type_name(kUeTypeNameFieldNumber, ue_type_name_default);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  ue_type_is_class(kUeTypeIsClassFieldNumber, false);
const std::string ue_origin_type_name_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  ue_origin_type_name(kUeOriginTypeNameFieldNumber, ue_origin_type_name_default);
const std::string ue_origin_type_default_value_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  ue_origin_type_default_value(kUeOriginTypeDefaultValueFieldNumber, ue_origin_type_default_value_default);
const std::string helper_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  helper(kHelperFieldNumber, helper_default);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  not_data_table(kNotDataTableFieldNumber, false);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::org::xresloader::ue::loader_mode, ::org::xresloader::ue::loader_mode_IsValid>, 14, false >
  default_loader(kDefaultLoaderFieldNumber, static_cast< ::org::xresloader::ue::loader_mode >(0));
const std::string include_header_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::RepeatedStringTypeTraits, 9, false >
  include_header(kIncludeHeaderFieldNumber, include_header_default);

// @@protoc_insertion_point(namespace_scope)
}  // namespace ue
}  // namespace xresloader
}  // namespace org
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
