// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xresloader.proto

#include "xresloader.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace org {
namespace xresloader {
}  // namespace xresloader
}  // namespace org
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_xresloader_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_xresloader_2eproto = nullptr;
const uint32_t TableStruct_xresloader_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_xresloader_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020xresloader.proto\022\016org.xresloader\032 goog"
  "le/protobuf/descriptor.proto*j\n\017ListStri"
  "pOption\022\026\n\022LIST_STRIP_DEFAULT\020\000\022\026\n\022LIST_"
  "STRIP_NOTHING\020\001\022\023\n\017LIST_STRIP_TAIL\020\002\022\022\n\016"
  "LIST_STRIP_ALL\020\003:7\n\020file_description\022\034.g"
  "oogle.protobuf.FileOptions\030\351\007 \001(\t:9\n\017msg"
  "_description\022\037.google.protobuf.MessageOp"
  "tions\030\351\007 \001(\t:A\n\027msg_require_mapping_all\022"
  "\037.google.protobuf.MessageOptions\030\363\007 \001(\010:"
  "7\n\rmsg_separator\022\037.google.protobuf.Messa"
  "geOptions\030\364\007 \001(\t:1\n\tvalidator\022\035.google.p"
  "rotobuf.FieldOptions\030\351\007 \001(\t:8\n\020field_uni"
  "que_tag\022\035.google.protobuf.FieldOptions\030\352"
  "\007 \003(\t:6\n\016field_not_null\022\035.google.protobu"
  "f.FieldOptions\030\353\007 \001(\010:9\n\021map_key_validat"
  "or\022\035.google.protobuf.FieldOptions\030\354\007 \001(\t"
  ":;\n\023map_value_validator\022\035.google.protobu"
  "f.FieldOptions\030\355\007 \001(\t:0\n\010verifier\022\035.goog"
  "le.protobuf.FieldOptions\030\361\007 \001(\t:9\n\021field"
  "_description\022\035.google.protobuf.FieldOpti"
  "ons\030\363\007 \001(\t:3\n\013field_alias\022\035.google.proto"
  "buf.FieldOptions\030\364\007 \003(\t:3\n\013field_ratio\022\035"
  ".google.protobuf.FieldOptions\030\365\007 \001(\005:7\n\017"
  "field_separator\022\035.google.protobuf.FieldO"
  "ptions\030\366\007 \001(\t:6\n\016field_required\022\035.google"
  ".protobuf.FieldOptions\030\367\007 \001(\010::\n\022field_o"
  "rigin_value\022\035.google.protobuf.FieldOptio"
  "ns\030\370\007 \001(\t:I\n!field_allow_missing_in_plai"
  "n_mode\022\035.google.protobuf.FieldOptions\030\371\007"
  " \001(\010:`\n\027field_list_strip_option\022\035.google"
  ".protobuf.FieldOptions\030\372\007 \001(\0162\037.org.xres"
  "loader.ListStripOption:;\n\023field_list_min"
  "_size\022\035.google.protobuf.FieldOptions\030\373\007 "
  "\001(\t:;\n\023field_list_max_size\022\035.google.prot"
  "obuf.FieldOptions\030\374\007 \001(\t:>\n\026field_list_s"
  "trict_size\022\035.google.protobuf.FieldOption"
  "s\030\375\007 \001(\010:1\n\tfield_tag\022\035.google.protobuf."
  "FieldOptions\030\376\007 \003(\t:9\n\021oneof_description"
  "\022\035.google.protobuf.OneofOptions\030\351\007 \001(\t:7"
  "\n\017oneof_separator\022\035.google.protobuf.Oneo"
  "fOptions\030\352\007 \001(\t:6\n\016oneof_not_null\022\035.goog"
  "le.protobuf.OneofOptions\030\353\007 \001(\010:I\n!oneof"
  "_allow_missing_in_plain_mode\022\035.google.pr"
  "otobuf.OneofOptions\030\354\007 \001(\010:1\n\toneof_tag\022"
  "\035.google.protobuf.OneofOptions\030\355\007 \003(\t:7\n"
  "\020enum_description\022\034.google.protobuf.Enum"
  "Options\030\351\007 \001(\t:=\n\021enumv_description\022!.go"
  "ogle.protobuf.EnumValueOptions\030\351\007 \001(\t:6\n"
  "\nenum_alias\022!.google.protobuf.EnumValueO"
  "ptions\030\352\007 \003(\tb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_xresloader_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_xresloader_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_xresloader_2eproto = {
  false, false, 1981, descriptor_table_protodef_xresloader_2eproto, "xresloader.proto", 
  &descriptor_table_xresloader_2eproto_once, descriptor_table_xresloader_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_xresloader_2eproto::offsets,
  nullptr, file_level_enum_descriptors_xresloader_2eproto, file_level_service_descriptors_xresloader_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_xresloader_2eproto_getter() {
  return &descriptor_table_xresloader_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_xresloader_2eproto(&descriptor_table_xresloader_2eproto);
namespace org {
namespace xresloader {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ListStripOption_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xresloader_2eproto);
  return file_level_enum_descriptors_xresloader_2eproto[0];
}
bool ListStripOption_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const std::string file_description_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FileOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  file_description(kFileDescriptionFieldNumber, file_description_default);
const std::string msg_description_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  msg_description(kMsgDescriptionFieldNumber, msg_description_default);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  msg_require_mapping_all(kMsgRequireMappingAllFieldNumber, false);
const std::string msg_separator_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  msg_separator(kMsgSeparatorFieldNumber, msg_separator_default);
const std::string validator_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  validator(kValidatorFieldNumber, validator_default);
const std::string field_unique_tag_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::RepeatedStringTypeTraits, 9, false >
  field_unique_tag(kFieldUniqueTagFieldNumber, field_unique_tag_default);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  field_not_null(kFieldNotNullFieldNumber, false);
const std::string map_key_validator_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  map_key_validator(kMapKeyValidatorFieldNumber, map_key_validator_default);
const std::string map_value_validator_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  map_value_validator(kMapValueValidatorFieldNumber, map_value_validator_default);
const std::string verifier_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  verifier(kVerifierFieldNumber, verifier_default);
const std::string field_description_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  field_description(kFieldDescriptionFieldNumber, field_description_default);
const std::string field_alias_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::RepeatedStringTypeTraits, 9, false >
  field_alias(kFieldAliasFieldNumber, field_alias_default);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< int32_t >, 5, false >
  field_ratio(kFieldRatioFieldNumber, 0);
const std::string field_separator_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  field_separator(kFieldSeparatorFieldNumber, field_separator_default);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  field_required(kFieldRequiredFieldNumber, false);
const std::string field_origin_value_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  field_origin_value(kFieldOriginValueFieldNumber, field_origin_value_default);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  field_allow_missing_in_plain_mode(kFieldAllowMissingInPlainModeFieldNumber, false);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::org::xresloader::ListStripOption, ::org::xresloader::ListStripOption_IsValid>, 14, false >
  field_list_strip_option(kFieldListStripOptionFieldNumber, static_cast< ::org::xresloader::ListStripOption >(0));
const std::string field_list_min_size_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  field_list_min_size(kFieldListMinSizeFieldNumber, field_list_min_size_default);
const std::string field_list_max_size_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  field_list_max_size(kFieldListMaxSizeFieldNumber, field_list_max_size_default);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  field_list_strict_size(kFieldListStrictSizeFieldNumber, false);
const std::string field_tag_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::RepeatedStringTypeTraits, 9, false >
  field_tag(kFieldTagFieldNumber, field_tag_default);
const std::string oneof_description_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::OneofOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  oneof_description(kOneofDescriptionFieldNumber, oneof_description_default);
const std::string oneof_separator_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::OneofOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  oneof_separator(kOneofSeparatorFieldNumber, oneof_separator_default);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::OneofOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  oneof_not_null(kOneofNotNullFieldNumber, false);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::OneofOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  oneof_allow_missing_in_plain_mode(kOneofAllowMissingInPlainModeFieldNumber, false);
const std::string oneof_tag_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::OneofOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::RepeatedStringTypeTraits, 9, false >
  oneof_tag(kOneofTagFieldNumber, oneof_tag_default);
const std::string enum_description_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  enum_description(kEnumDescriptionFieldNumber, enum_description_default);
const std::string enumv_description_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  enumv_description(kEnumvDescriptionFieldNumber, enumv_description_default);
const std::string enum_alias_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::RepeatedStringTypeTraits, 9, false >
  enum_alias(kEnumAliasFieldNumber, enum_alias_default);

// @@protoc_insertion_point(namespace_scope)
}  // namespace xresloader
}  // namespace org
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
