// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xresloader_ue.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_xresloader_5fue_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_xresloader_5fue_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_xresloader_5fue_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_xresloader_5fue_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_xresloader_5fue_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace org {
namespace xresloader {
namespace ue {

enum loader_mode : int {
  EN_LOADER_MODE_DEFAULT = 0,
  EN_LOADER_MODE_ENABLE = 1,
  EN_LOADER_MODE_DISABLE = 2,
  loader_mode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  loader_mode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool loader_mode_IsValid(int value);
constexpr loader_mode loader_mode_MIN = EN_LOADER_MODE_DEFAULT;
constexpr loader_mode loader_mode_MAX = EN_LOADER_MODE_DISABLE;
constexpr int loader_mode_ARRAYSIZE = loader_mode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* loader_mode_descriptor();
template<typename T>
inline const std::string& loader_mode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, loader_mode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function loader_mode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    loader_mode_descriptor(), enum_t_value);
}
inline bool loader_mode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, loader_mode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<loader_mode>(
    loader_mode_descriptor(), name, value);
}
// ===================================================================


// ===================================================================

static const int kKeyTagFieldNumber = 1101;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< int64_t >, 3, false >
  key_tag;
static const int kUeTypeNameFieldNumber = 1102;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  ue_type_name;
static const int kUeTypeIsClassFieldNumber = 1103;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  ue_type_is_class;
static const int kUeOriginTypeNameFieldNumber = 1104;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  ue_origin_type_name;
static const int kUeOriginTypeDefaultValueFieldNumber = 1105;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  ue_origin_type_default_value;
static const int kHelperFieldNumber = 1101;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  helper;
static const int kNotDataTableFieldNumber = 1102;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  not_data_table;
static const int kDefaultLoaderFieldNumber = 1103;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::org::xresloader::ue::loader_mode, ::org::xresloader::ue::loader_mode_IsValid>, 14, false >
  default_loader;
static const int kIncludeHeaderFieldNumber = 1104;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::RepeatedStringTypeTraits, 9, false >
  include_header;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ue
}  // namespace xresloader
}  // namespace org

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::org::xresloader::ue::loader_mode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::org::xresloader::ue::loader_mode>() {
  return ::org::xresloader::ue::loader_mode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_xresloader_5fue_2eproto
